# Generated by Django 6.0.8 on 2026-08-17 08:15

from django.db import migrations

def load_payment_methods(apps, schema_editor) : 
    PaymentMethod = apps.get_model(
        "payment_methods" , 
        "PaymentMethod" ,
    )

    payment_methods = [
        {"name": "UPI", "is_active": True},
        {"name": "Credit Card", "is_active": True},
        {"name": "Cash on Delivery", "is_active": True},
        {"name": "Net Banking", "is_active": True},
        {"name": "CodeCredits", "is_active": False},
    ]


    for method in payment_methods : 
        PaymentMethod.objects.get_or_create(
            name = method["name"] , 
            defaults = {
                "is_active" : method["is_active"] ,
            } ,
        )

def unload_payment_methods(apps, schema_editor)  :
    PaymentMethod = apps.get_model(
        "payment_methods",
        "PaymentMethod",
    )

    PaymentMethod.objects.filter(
        name__in=[
            "UPI",
            "Credit Card",
            "Cash on Delivery",
            "Net Banking",
            "CodeCredits",
        ]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_alter_paymentmethod_options'),
    ]

    operations = [
        migrations.RunPython(
            load_payment_methods,
            unload_payment_methods,
        ),
    ]
