APP_NAME = 'payment_gateway'

PAYMENT_GATEWAY_ROUTE = "payment-gateway"
PAYMENT_GATEWAY_BASENAME = "payment-gateway"

PAYMENT_SUCCESS_RATE = 0.9

PAYMENT_STATUS_PROCESSING = "PROCESSING"
PAYMENT_STATUS_SUCCESS = "SUCCESS"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_CREATED = "CREATED"

DUMMY_SIGNATURE = "VALID_SIGNATURE"

MAX_AMOUNT_PRICE = 10
AMOUNT_DECIMAL_PLACES = 2