# Generated by Django 6.0.8 on 2026-08-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
